// Kodlayalım — Çizim Atölyesi ipuçları: her bölüm için [düşündüren soru, somut ipucu]. Üçüncü basamak bölümün örnek çözümüdür.
(function (root) {
    'use strict';
    const IPUCLARI = [
        /* 1 */['Robot hangi yöne bakıyor? Çizgi ne kadar uzun olmalı? Tuvaldeki soluk çizgiye bak.', '"ileri git" bloğunu "çalıştırınca" bloğunun altına bırak ve sayıyı <b>200</b> yap.'],
        /* 2 */['Köşede robot ne kadar dönüyor? Dik bir köşe kaç derecedir?', 'Önce ileri git, sonra <b>sağa dön 90°</b>, sonra yine ileri git. İki çizgi de 150 adım.'],
        /* 3 */['Karenin her kenarında robot aynı şeyi mi yapıyor?', 'Dört kez: ileri git 100, sağa dön 90. Son kenardan sonra dönmene gerek yok.'],
        /* 4 */['Bir önceki bölümde aynı iki bloğu kaç kez yazdın? Bunu tek seferde söyleyebilir misin?', '"tekrarla 4 kez" bloğunun içine <b>ileri git 100</b> ve <b>sağa dön 90</b> koy.'],
        /* 5 */['Merdivenin bir basamağı hangi hareketlerden oluşuyor?', 'Bir basamak: ileri 45, sağa 90, ileri 45, sola 90. Bunu 5 kez tekrarla.'],
        /* 6 */['Robot üçgenin her köşesinde ne kadar dönmeli? Üç köşede toplam bir tam tur (360°) döner.', '360 ÷ 3 = 120. <b>tekrarla 3 kez</b>: ileri 160, sağa dön 120.'],
        /* 7 */['Altıgenin kaç köşesi var? Toplam dönüş yine 360°.', '360 ÷ 6 = 60. <b>tekrarla 6 kez</b>: ileri 80, sağa dön 60.'],
        /* 8 */['Çok küçük adımlar ve çok küçük dönüşlerle yuvarlak bir şekil çizilebilir mi?', '<b>tekrarla 36 kez</b>: ileri 10, sağa dön 10. 36 × 10° = 360°, yani tam bir tur.'],
        /* 9 */['Kesikli çizgide robot bir parça çiziyor, bir parça boş geçiyor. Kalem nerede kalkıp nerede iniyor?', '<b>tekrarla 8 kez</b>: ileri 20, kalemi kaldır, ileri 20, kalemi indir.'],
        /* 10 */['Her kenar farklı renkte. Rengi ne zaman değiştirmelisin: çizgiden önce mi, sonra mı?', 'Her kenardan <b>önce</b> renk bloğunu koy: kırmızı → ileri 160 → sağa 120, mavi → …, yeşil → …'],
        /* 11 */['Yıldızın uçları çok sivri. Robot her uçta 90°\'den çok mu az mı dönüyor?', '<b>tekrarla 5 kez</b>: ileri 180, sağa dön <b>144</b>.'],
        /* 12 */['Desen aynı kareden oluşuyor, kareler biraz dönmüş. Kaç kare var, her biri ne kadar dönmüş?', 'İçte kare: <b>tekrarla 4</b> (ileri 90, sağa 90). Dışta <b>tekrarla 6</b> ve her kareden sonra <b>sağa 60</b>.'],
        /* 13 */['Aynı kare üç kez çiziliyor. Kareyi bir kez tanımlayıp tekrar tekrar kullanabilir misin?', '"fonksiyon kare" içine kareyi (tekrarla 4: ileri 70, sağa 90) koy. Sonra 3 kez: kare çağır, kalemi kaldır, sağa 90, ileri 100, sola 90, kalemi indir.'],
        /* 14 */['Sarmalın her kenarı bir öncekinden uzun. Uzunluğu her turda artan bir sayı nasıl yazılır?', '<b>i sayacı: 10\'dan 300\'e, 10\'ar artarak</b> bloğunun içine "ileri git <b>i</b>" ve "sağa dön 90" koy.'],
        /* 15 */['Çiçek, birbirinin etrafında dönen dairelerden oluşuyor. Kaç daire var?', 'İçte daire: tekrarla 36 (ileri 6, sağa 10). Dışta tekrarla 10, her daireden sonra sağa <b>36</b> (360 ÷ 10). Rengi pembe yap.'],
        /* 16 */['Kar tanesinin bir kolunu çiz: çizgi ve ucunda V. Kol çizildikten sonra robot nereye dönmeli?', 'Kolu fonksiyon yap; sonunda <b>geri git 80</b> ile merkeze dön. Ana kodda tekrarla 6: kol çağır, sağa 60. Rengi mavi yap.'],
        /* 17 */['Dikdörtgenin karşılıklı kenarları eşit. Uzun ve kısa kenar birlikte kaç kez tekrar ediyor?', '<b>tekrarla 2 kez</b>: ileri 220, sağa 90, ileri 120, sağa 90.'],
        /* 18 */['Beşgende robot her köşede ne kadar döner?', '360 ÷ 5 = 72. <b>tekrarla 5</b>: ileri 130, sağa dön 72.'],
        /* 19 */['Sekizgen, dur levhası. 8 köşe, toplam 360°.', '360 ÷ 8 = 45. <b>tekrarla 8</b>: ileri 80, sağa dön 45.'],
        /* 20 */['Tam daire 36 adımdı. Yarım daire için kaç adım gerekir?', '<b>tekrarla 18</b>: ileri 18, sağa 10. 18 × 10° = 180°, yarım tur.'],
        /* 21 */['Eşkenar dörtgende iki farklı köşe var: biri sivri, biri geniş. Robot her köşede ne kadar dönüyor?', '<b>tekrarla 2</b>: ileri 150, sağa <b>60</b>, ileri 150, sağa <b>120</b>.'],
        /* 22 */['Önce duvarları (kare), sonra çatıyı (üçgen) çiz. Kare bitince robot nerede ve nereye bakıyor?', 'Kare: tekrarla 4 (ileri 140, sağa 90). Sonra ileri 140 ile çatının köşesine çık, sağa 30, ve tekrarla 2 (ileri 140, sağa 120).'],
        /* 23 */['Pencere dört kareden oluşuyor ve hepsi ortada buluşuyor. Bir kare bitince robot ne yapmalı?', 'İçte kare: tekrarla 4 (ileri 100, sağa 90). Dışta tekrarla 4, her kareden sonra sağa 90.'],
        /* 24 */['Her kenar ayrı renk. Renk bloğunu hangi kenardan önce koymalısın?', 'Kırmızı → ileri 180 → sağa 90, sarı → ileri 180 → sağa 90, yeşil → …, mavi → ileri 180.'],
        /* 25 */['Kalem kalınlaşınca çizim değişir. Kalınlık ve rengi çizmeye başlamadan önce mi ayarlamalısın?', 'En başa <b>renk mor</b> ve <b>kalınlık 10</b> koy, sonra tekrarla 3: ileri 200, sağa 120.'],
        /* 26 */['Daireyi çizerken bir parça çiz, bir parça boş bırak. Kalem kalkıkken robot dönmeye devam etmeli mi?', 'tekrarla 18: ileri 15, sağa 10, kalemi kaldır, ileri 15, sağa 10, kalemi indir.'],
        /* 27 */['Kenar kesikli; kenar bitince köşede dönmek gerekiyor. Hangi döngü içte, hangisi dışta?', 'İçte kesikli kenar: tekrarla 5 (ileri 20, kalem kaldır, ileri 20, kalem indir). Dışta tekrarla 4, her kenardan sonra sağa 90.'],
        /* 28 */['Üç daire alt alta. Bir daireden sonrakine çizgi çekmeden nasıl geçersin?', 'Daire: tekrarla 36 (ileri 9, sağa 10). Aralarda: kalemi kaldır, sağa 90, ileri 115, sola 90, kalemi indir. Her daireden önce rengi değiştir.'],
        /* 29 */['Merkezden çıkan her çizgide robot gidip geri geliyor. Geri gelince ne kadar dönmeli?', '<b>tekrarla 12</b>: ileri 150, geri 150, sağa 30 (360 ÷ 12).'],
        /* 30 */['Güneşin çevresi bir daire, ışınlar da daireden dışarı çıkıyor. Daireyi çizerken ışınları da çizebilir misin?', 'tekrarla 18: ileri 20, sola 90, ileri 40, geri 40, sağa 90, sağa 20. Rengi turuncu yap.'],
        /* 31 */['Desen üçgenlerden oluşuyor. Kaç üçgen var ve her biri öncekinden ne kadar dönmüş?', 'İçte üçgen: tekrarla 3 (ileri 120, sağa 120). Dışta tekrarla 12, her üçgenden sonra sağa 30.'],
        /* 32 */['Çiçeğin her yaprağı bir altıgen. Kaç altıgen var?', 'İçte altıgen: tekrarla 6 (ileri 55, sağa 60). Dışta tekrarla 6, her altıgenden sonra sağa 60.'],
        /* 33 */['Önce bir sırada üç kareyi yan yana çiz. Sonra bir alt sıraya geçmek için robot ne yapmalı?', 'Sıra: tekrarla 3 (kare, ileri 60). Sıradan sonra: kalemi kaldır, geri 180, sağa 90, ileri 60, sola 90, kalemi indir. Bunu 3 sıra tekrarla.'],
        /* 34 */['Altıgen bitince robot başlangıç noktasında. Sonraki altıgen hangi köşeden başlıyor?', 'Altıgen: tekrarla 6 (ileri 50, sağa 60). Sonra alt kenarlardan yürü: sağa 120, ileri 50, sola 60, ileri 50, sola 60. Hepsini 3 kez tekrarla.'],
        /* 35 */['Aynı üçgen dört kez çiziliyor. Üçgeni fonksiyon yaparsan aralarında robot ne kadar ilerlemeli?', '"fonksiyon ucgen": tekrarla 3 (ileri 70, sola 120). Ana kod: tekrarla 4 (ucgen çağır, ileri 80).'],
        /* 36 */['Çam ağacının üç katı aynı şekil. Bir katı çizdikten sonra robot bir üst kata nasıl çıkar?', 'Önce gövde (kahverengi, ileri 50), sonra yeşil ve sağa 90. Kat fonksiyonu bir üçgen çizer; her kattan sonra kalemi kaldır, sola 90, ileri 60, sağa 90, kalemi indir.'],
        /* 37 */['Çitin her direği aynı: yukarı çık, sivri tepe, aşağı in. Direk bitince robot bir sonrakine nasıl geçer?', 'Direk: ileri 80, sağa 45, ileri 14, sağa 90, ileri 14, sağa 45, ileri 80, sola 90, ileri 20, sola 90. Bunu fonksiyon yap ve 6 kez çağır.'],
        /* 38 */['Üç yıldız aynı. Yıldızları birbirine çizgiyle bağlamadan yan yana nasıl dizersin?', '"fonksiyon yildiz": tekrarla 5 (ileri 80, sağa 144). Ana kod: sarı renk, tekrarla 3 (yildiz çağır, kalemi kaldır, ileri 115, kalemi indir).'],
        /* 39 */['Araba bir dikdörtgen ve iki tekerlekten oluşuyor. İki tekerlek aynıysa fonksiyon kullanabilir misin?', 'Gövde: kırmızı, tekrarla 2 (ileri 220, sola 90, ileri 70, sola 90). Teker: tekrarla 18 (ileri 8, sağa 20). Tekerlerin arasında kalem kalkık ileri git.'],
        /* 40 */['Pervane dört kareden oluşuyor. Kare için bir fonksiyon, pervane için başka bir fonksiyon yazabilir misin?', 'kare: tekrarla 4 (ileri 50, sağa 90). pervane: tekrarla 4 (kare çağır, sağa 90). Pervaneyi iki kez çağır; arada kalem kalkıkken sağa 90, ileri 170, sola 90.'],
        /* 41 */['Her kenar bir öncekinden biraz uzun ve robot hep aynı açıyla dönüyor. Üçgen için açı kaç?', 'Sayaç: <b>i 10\'dan 250\'ye, 12\'şer artarak</b>; içinde ileri <b>i</b>, sağa 120.'],
        /* 42 */['Altıgen sarmalda dönüş açısı kaç olmalı? Sayaç kaçar artmalı?', 'Sayaç: <b>i 4\'ten 160\'a, 4\'er artarak</b>; içinde ileri i, sağa 60.'],
        /* 43 */['Bütün kareler aynı köşeden başlıyor ve büyüyor. Sayaç neyi göstermeli: kenar uzunluğunu mu, kare sayısını mı?', 'Sayaç kenar uzunluğu: <b>i 30\'dan 330\'a, 50\'şer</b>. İçinde tekrarla 4 (ileri i, sağa 90).'],
        /* 44 */['Kare sarmalda 90° dönersek düz bir sarmal çıkar. Biraz fazla dönersek ne olur?', 'Sayaç: <b>i 4\'ten 260\'a, 4\'er</b>; içinde ileri i, sağa <b>91</b>.'],
        /* 45 */['Yelpazede her çizgi bir öncekinden uzun ve robot her seferinde merkeze dönüyor. Geri gelmek için hangi blok?', 'Sayaç: i 20\'den 200\'e, 20\'şer; içinde ileri i, <b>geri i</b>, sağa 18.'],
        /* 46 */['Her basamak hem daha geniş hem daha yüksek. Aynı sayaç iki yerde de kullanılabilir mi?', 'Sayaç: i 10\'dan 70\'e, 15\'er; içinde ileri i, sola 90, ileri i, sağa 90.'],
        /* 47 */['Bir yaprak iki yaydan oluşuyor. Yay nasıl çizilir: küçük adımlar ve küçük dönüşlerle!', 'yaprak: tekrarla 2 (tekrarla 9: ileri 12, sağa 10; sonra sağa 90). Ana kod: mor renk, tekrarla 12 (yaprak çağır, sağa 30).'],
        /* 48 */['Bir sırayı (4 kare) fonksiyon yap. Sıra bitince robot sıranın başına nasıl döner?', 'sira: tekrarla 4 (kare, ileri 70). Ana kod: tekrarla 4 (sira, kalemi kaldır, geri 280, sağa 90, ileri 70, sola 90, kalemi indir).'],
        /* 49 */['Bir çatal: sola eğik çizgi, sağa eğik çizgi, ortaya dönüş. Kolun üstünde kaç çatal var?', 'catal: sola 45, ileri 30, geri 30, sağa 90, ileri 30, geri 30, sola 45. kol: ileri 60, catal, ileri 60, catal, geri 120. Ana kod: tekrarla 6 (kol, sağa 60).'],
        /* 50 */['Binalar soldan sağa yükseliyor. Bir binanın yüksekliğini sayaçla verebilir misin?', 'Sayaç: i 60\'tan 220\'ye, 40\'ar. İçinde: ileri i, sağa 90, ileri 40, sağa 90, ileri i, sola 90, ileri 20, sola 90. Rengi gri yap.']
    ];
    if (typeof module !== 'undefined' && module.exports) module.exports = IPUCLARI;
    else root.CIZIM_IPUCLARI = IPUCLARI;
})(typeof window !== 'undefined' ? window : globalThis);
